skip_tags: true

matrix:
  fast_finish: true

os: Visual Studio 2015

environment:
  matrix:
    - PLATFORM: "x64"
      VCBUILD: "vcbuild64.bat"
      RUNTEST: "runtest64.bat"
      PYTHON: "C:\\Python36-x64"
      MINICONDA: C:\\Miniconda3
      PYTHON_VERSION: 3.7

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

before_build:
  "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" %PLATFORM%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - "conda create -q -n pylibtiff-dev python=%PYTHON_VERSION% numpy pytest pip"
  - conda activate pylibtiff-dev
  - pip install .

test_script:
  - pytest -sv libtiff